apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      timeInterval: 10s
      queryTimeout: 30s
      httpMethod: POST

  - name: Vali
    type: vali
    access: proxy
    url: http://vali:3100
