  # datasource URL: http://localhost:3100/
  loki:
    image: plutono/loki:master
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  promtail:
    image: plutono/promtail:master
    volumes:
      - ./docker/blocks/loki/config.yaml:/etc/promtail/docker-config.yaml
      - /var/log:/var/log
      - ../data/log:/var/log/plutono
    command:
      -config.file=/etc/promtail/docker-config.yaml
