# This will proxy all requests for http://localhost:10081/plutono/ to
# http://localhost:3000 (Plutono running locally)
#
# Please note that you'll need to change the root_url in the Plutono configuration:
# root_url = %(protocol)s://%(domain)s:10081/plutono/

  apacheproxy:
    build: docker/blocks/apache_proxy
    network_mode: host
