  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831"
      - "16686:16686"
  # Additional vali to generate some traces
  # datasource URL: http://localhost:3100/
  vali:
    image: ghcr.io/credativ/vali:main
    ports:
      - "3100:3100"
    command: -config.file=/etc/vali/local-config.yaml
    # For this to work you need to install the logging driver see https://github.com/credativ/vali/tree/main/cmd/docker-driver#plugin-installation
    logging:
      driver: vali
      options:
        vali-url: "http://localhost:3100/vali/api/v1/push"
    # Optional jaeger tracing
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
  promtail:
    image: plutono/promtail:master
    volumes:
      - ./docker/blocks/vali/config.yaml:/etc/promtail/docker-config.yaml
      - /var/log:/var/log
      - ../data/log:/var/log/plutono
    command:
      -config.file=/etc/promtail/docker-config.yaml

