version: '3'

services:
  traefik:
    image: traefik:v2.1
    volumes:
      - './traefik.yml:/etc/traefik/traefik.yml'
      - './configs:/etc/traefik/configs'
    ports:
      - '80:80'
      - '8080:8080'
    links:
      - plutono-subpath

  plutono-subpath:
    image: plutono/plutono:latest
    environment:
      - PL_SERVER_ROOT_URL=/plutono
      - PL_SERVER_SERVE_FROM_SUB_PATH=true
