  openldap:
    container_name: ldap
    build: docker/blocks/openldap
    environment:
      SLAPD_PASSWORD: plutono
      SLAPD_DOMAIN: plutono.org
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "389:389"


