  admins-openldap:
    build: 
      context: docker/blocks/multiple-openldap
      dockerfile: ./admins-ldap-server.Dockerfile
    environment:
      SLAPD_PASSWORD: plutono
      SLAPD_DOMAIN: plutono.org
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "389:389"

  openldap:
    build: 
      context: docker/blocks/multiple-openldap
      dockerfile: ./ldap-server.Dockerfile
    environment:
      SLAPD_PASSWORD: plutono
      SLAPD_DOMAIN: plutono.org
      SLAPD_ADDITIONAL_MODULES: memberof
    ports:
      - "388:389"


