http:
  middlewares:
    compress-response:
      compress: {}

  services:
    plutono-subpath:
      loadBalancer:
        servers:
          - url: 'http://plutono-subpath:3000/'

  routers:
    plutono-subpath:
      entryPoints:
        - web
      middlewares:
        - compress-response
      rule: 'Path(`/plutono`) || PathPrefix(`/plutono/`)'
      service: plutono-subpath
