# This will proxy all requests for http://localhost:10080/plutono/ to
# http://localhost:3000 (Plutono running locally)
#
# Please note that you'll need to change the root_url in the Plutono configuration:
# root_url = %(protocol)s://%(domain)s:10080/plutono/

  nginxproxy:
    build: docker/blocks/nginx_proxy
    network_mode: host
