name: Backend unit tests

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  unit-test-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.1
          cache: true
          cache-dependency-path: |
              **/go.sum
              **/go.mod

      - name: Linter
        run: make lint-go

      - name: Test
        run: go test -v -covermode=atomic -tags=integration ./pkg/...
